### ISSUE TITLE
Dramatic sound effect

### ISSUE THREAD

**Issue by fluks** [gregnk/2038#1]
Hi! I watched a video about this problem and I  searched for countdown page and I found yours. I thought it would be funny to have the dramatic countdown sound effect from the 24 TV series if you know that. This kind https://www.youtube.com/watch?v=zoe_uDla4p0 But maybe you want to keep your page as informational only and not a meme page 😄

**Comment by gregnk** [comment]
As you said, I don't intend on this being a meme page. So, no.
